name: Security Bunnies
favicon: null
layout_spectrum: 0.6489362
typography_spectrum: 0.4262053808197379
title: Information Security for all the bunnies who want to stay safe online
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7C3F24'
    - '#B77448'
    - '#FFFFFE'
    - '#111111'
    - '#B3D8DC'
  brandStrength: 0.9148936
  lightness: 0.931588567327708
  saturation: 0.4999842676334083
  rhythmicContrast: 0.7060691537335515
purpose: []
