name: Security Bunnies
favicon: null
layout_spectrum: 0.6253119306638837
typography_spectrum: 0.4262053808197379
title: Information Security for all the bunnies who want to stay safe online
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.43610477657057345
  lightness: 0.931588567327708
  saturation: 0.4999842676334083
  rhythmicContrast: 0.7060691537335515
purpose: []
