title: Information Security for all the bunnies who want to stay safe online
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8339599
  brandStrength: 0.9148936
  lightness: 0
  brandColors:
    - '#7C3F24'
    - '#B77448'
    - '#FFFFFE'
    - '#111111'
    - '#B3D8DC'
  rhythmicContrast: 0.8195488
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Security Bunnies
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7431078
layout_spectrum: 0.01441103
