title: Information Security for all the bunnies who want to stay safe online
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4999842676334083
  brandStrength: 0.4361047765705734
  rhythmicContrast: 0.7060691537335515
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  lightness: 0.931588567327708
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Security Bunnies
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4262053808197379
layout_spectrum: 0.9957447
